name: CI
on:
  push: #run when `git push` or `merge a pull request` into the master branch
    branches:
    - master
  pull_request: #run `merge a pull request` into the master branch
    branches:
    - master
jobs:
    build_and_test:
      runs-on: ubuntu-18.04
      steps:
      - name: checkout
      - uses: actions/checkout@v2
      - name: compile
      - run: gcc -Wall main.c -o mai
      - name: test
      - run: ./main
